language: node_js
node_js:
  - '10'
install:
  - npm install
  - npm run install-front

before_script:
  - npm run test
script:
  - npm run build
  - npm run build-front
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: morcilla-conf-hackathon
  on: $DEPLOY_BRANCH
